language: go
go:
- 1.8.x
- 1.9.x
- 1.10.x
- tip
script:
- script/lint
- script/test
- script/coverage
env:
  global:
  - secure: MhSN72uI6JxWLQMN6137IAyF1oWyihpCexaSi03PYVb/qd+aGYNPXEqyHYQUY9ZE9CpimBPmLFAYkFKPYt25roVjEuI/vs63rD8nvpdMXmvU8iwM4+y3/CQ2PDHvZIrfwOaBNOtzktxSY4FLECL0WalkqCOdW1pIf5C+JH8ZtY5B+wsVtWbtKe8CqINzD5xw/eAqG4n79sTQTrUCxI6A3IV/3MEKodAnbvozwnsd/RrzqUaapDp+ZAZbkqgrl6tq/wMfjbyl+81duDgiy9pp3f0a8aTlDm9cMVUWA9bS5QhHR0oxtX+er9Dbfq2vKtmeayr2RNu7rscdLh1/cnJRoHr3ViYgLjDiCopbeiH11PLooaVSpPIqssCk/AEQNM25bQ2Dvs1cxeHNOI9nr8/SKpgblKBm+Jku0c/q3odZj834l0wvCZlo2oSCojGAz5IQl3TWr1DcxpATTJOIVXTsgQTDCHyO8QTTM76XfXlVe53mFk4DzG1i1BJPN5Puihz1l0eaTueFQkhpIHKbL8YWGoHXbqbd2H8Av9XhYuOTZ/SDpasp3aO4dn7cG0hRqVsFYE7DcCiXirGV+hFL8sa9uW6n3jr1LjoEX27V1FSpYM9OuDlwfbOmwdx2nfL+yuyDvI6lCjn/DjYSxrqp53GQdisrAsmTxfL4LhoMaNR5N9Q=
  - secure: AlA2lNpwilMZaBPwhvyxQhp0SV0/0wbIpmx7rkSHuSZYiVIq7NBsfaMOTOABKKF6FDuduHi/C9Ajywykp2dpKP5QVptx1/tklft/PSnZ4zd3b+wFvC/z/EoloTTTecFjGV1qYOU1MBbPNe4ExTnnm7whXFPQ4s7qj73AFROE1XgPZTuHv0OuLg5RKAYb/FYH/JVXJSmMAC/IE97XaVlgmkVK6sI8H+R+B30KB2L6DeQDKCisWr1UywdbXeEYU4gYV/JDhlg93MCiPRijOFOvLj0uKikDMVVFvdi3JDxz5KH85AiWXdNGyijjmhxDQU+R/nZCODhrXwtKoriB2brBD2yI3y00GrnyPhDdRJshNgwnGLt4BwJgcA8+kI+f9ScQAXgmU4mOEtTx34PUEbJIiUQAhbOMh33w3O5AKmSeplSupdykaYo6FuV4bwmnE8pzH1H4Ba0r9qVW4vVPqt4Kp2uCs2dewkAIAW7QdvIEZ+Z9joo3KiddOdGLs2v27MyVN3rMjvZIlKraJrjxzv/WyyEmkYpZ3Pa0iCbLJfqCLE5Lt9fqmZ3ovmHAwuFQtTLnEkOllfyT2wn09yw3/6gS3FqKknEHAsLAOQmk1HHJR5aHB0mrZcRnr/kUQYuKTjPHuomG6k0WXt00MoKudWtePmvE/q8g8yErw8Ud8P1uLVE=
